### ISSUE TITLE
Hi, where can I get sfcc-driver?

### ISSUE THREAD

**Issue by ArchCangyuan** [mcrl/soff-compiler#1]
According to your manual, there should be a script called _sfcc-driver_ in the bin folder after installing. However, I followed the steps described in the manual and the procedure alerted the lost of the file. So how can I get it?

**Comment by csehydrogen** [comment]
Hi, [soff-hardware-opae](https://github.com/mcrl/soff-hardware-opae) provides support for OPAE hardware and _sfcc-driver_.

**Comment by ArchCangyuan** [comment]
Thank you!
