### ISSUE TITLE
Is this project changed from LLVM?

### ISSUE THREAD

**Issue by panyan928** [mcrl/soff-compiler#2]
Hi, I'm studying this project, this work is so great but I'm not good at compiler. 
I see this project maybe from LLVM, is it ? I want to ask you about the main changes. 
Thank you very much.

**Comment by csehydrogen** [comment]
Hi, this project bases on the old version of LLVM. (around 3.8 IIRC)
Main changes are:
* https://github.com/mcrl/soff-compiler/blob/master/compiler/tools/clang/tools/driver/snuclcc_main.cpp
* All directories that starts with "Snu" inside https://github.com/mcrl/soff-compiler/tree/master/compiler/tools/clang/lib
